# Generated by Django 5.2 on 2025-04-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigilance_dt', models.DateField()),
                ('vigilance_subject', models.CharField(max_length=200)),
                ('vigilance_complainant', models.CharField(max_length=200)),
                ('vigilance_contents', models.TextField(blank=True, null=True)),
                ('vigilance_inward_dt', models.DateField()),
                ('vigilance_outward_ref', models.CharField(blank=True, max_length=60, null=True)),
                ('vigilance_outward_dt', models.DateField()),
                ('vigilance_subject_file', models.FileField(blank=True, null=True, upload_to='vig_subject')),
                ('vigilance_reply_file', models.FileField(blank=True, null=True, upload_to='vig_reply')),
                ('vigilance_pending', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Replied', 'Replied')], null=True)),
                ('vigilance_remarks', models.TextField(blank=True, null=True)),
                ('vigilance_updated', models.DateTimeField(auto_now=True)),
                ('vigilance_created', models.DateTimeField(auto_now_add=True)),
                ('vigilance_hod', models.ManyToManyField(blank=True, to='vigilance.hod')),
            ],
            options={
                'ordering': ['-vigilance_inward_dt'],
            },
        ),
    ]
