# Generated by Django 5.2 on 2025-04-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilance', '0001_initial'),
        ('vip_ref', '0002_alter_reference_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reference',
            new_name='Vigilance',
        ),
        migrations.DeleteModel(
            name='HOD',
        ),
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_hod',
            field=models.ManyToManyField(blank=True, to='vip_ref.hod'),
        ),
    ]
