# Generated by Django 5.2 on 2025-05-07 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilance', '0002_rename_reference_vigilance_delete_hod_and_more'),
        ('vip_ref', '0009_alter_reference_outward_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vigilance',
            name='vigilance_eoffice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigilance',
            name='vigilance_hod_reply',
            field=models.ManyToManyField(blank=True, related_name='HOD_reply', to='vip_ref.hod'),
        ),
        migrations.AddField(
            model_name='vigilance',
            name='vigilance_ref_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_hod',
            field=models.ManyToManyField(blank=True, related_name='HOD', to='vip_ref.hod'),
        ),
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_reply_file',
            field=models.FileField(blank=True, default='/images/BLANK.pdf', null=True, upload_to='vig_reply'),
        ),
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_subject_file',
            field=models.FileField(blank=True, default='/images/BLANK.pdf', null=True, upload_to='vig_subject'),
        ),
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilance.complainant'),
        ),
    ]
