# Generated by Django 5.2 on 2025-04-30 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilance', '0002_rename_reference_vigilance_delete_hod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Address', models.TextField(blank=True, null=True)),
                ('mobile', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='vigilance',
            name='vigilance_eoffice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigilance.complainant'),
        ),
    ]
