# Generated by Django 5.2 on 2025-04-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilance', '0003_complainant_vigilance_vigilance_eoffice_and_more'),
        ('vip_ref', '0004_alter_reference_outward_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_hod',
            field=models.ManyToManyField(blank=True, related_name='HOD', to='vip_ref.hod'),
        ),
    ]
