# Generated by Django 5.2 on 2025-05-07 11:25

import vigilance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilance', '0003_complainant_vigilance_vigilance_eoffice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_reply_file',
            field=models.FileField(blank=True, default=vigilance.models.get_default, null=True, upload_to='vig_reply'),
        ),
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_subject_file',
            field=models.FileField(blank=True, default=vigilance.models.get_default, null=True, upload_to='vig_subject'),
        ),
    ]
