# Generated by Django 5.2 on 2025-05-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilance', '0004_alter_vigilance_vigilance_hod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complainant',
            old_name='Address',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='complainant',
            name='mobile',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
