# Generated by Django 5.2 on 2025-05-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilance', '0004_alter_vigilance_vigilance_reply_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_inward_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_outward_dt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
