# Generated by Django 5.2 on 2025-06-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilance', '0005_alter_vigilance_vigilance_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigilance',
            name='vigilance_inward_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
