# Generated by Django 5.2 on 2025-05-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilance', '0006_alter_complainant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainant',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
