# Generated by Django 5.2 on 2025-06-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigilance', '0006_vigilance_vigilance_inward_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_inward_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_inward_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inward DP No.'),
        ),
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_outward_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_outward_ref',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Outward Reference No.'),
        ),
        migrations.AlterField(
            model_name='vigilance',
            name='vigilance_ref_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference No. (VIGILANCE)'),
        ),
    ]
