# Generated by Django 5.2 on 2025-04-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_type', models.CharField(choices=[('1', 'Chair Normal'), ('2', 'Table'), ('3', 'Almirah'), ('4', 'Bookself'), ('5', 'PC'), ('6', 'Printer'), ('7', 'Color Printer'), ('8', 'Chair Executive')])),
                ('furniture_qty', models.IntegerField(blank=True, null=True)),
                ('furniture_dt_receipt', models.DateField(blank=True, null=True)),
                ('furniture_make', models.CharField(max_length=60)),
                ('furniture_model', models.CharField(max_length=60)),
                ('furniture_serial', models.CharField(max_length=60)),
                ('furniture_room', models.CharField(choices=[('2103', 'HR Director Room'), ('2104', 'HR TS Room'), ('2105', 'HR Staff Room'), ('2106', 'HR Visting Room'), ('2107', 'HR Rest Room')])),
                ('furniture_image', models.ImageField(blank=True, null=True, upload_to='furniture')),
                ('furniture_remarks', models.TextField(blank=True, null=True)),
                ('furniture_updated', models.DateTimeField(auto_now=True)),
                ('furniture_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-furniture_updated', '-furniture_created'],
            },
        ),
    ]
