# Generated by Django 5.2 on 2025-05-08 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='furniture',
            options={'ordering': ['-furniture_dt_receipt']},
        ),
        migrations.AlterField(
            model_name='furniture',
            name='furniture_image',
            field=models.ImageField(blank=True, null=True, upload_to='assets'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='furniture_model',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='furniture_qty',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='furniture_room',
            field=models.CharField(choices=[('2310', 'HR Director Room'), ('2311', 'HR TS Room'), ('2313', 'HR Staff Room'), ('231V', 'HR Visting Room'), ('2308', 'HR Conference Room'), ('231R', 'HR Rest Room')]),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='furniture_serial',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='furniture_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniture.assetdesc'),
        ),
    ]
