# Generated by Django 5.2 on 2025-04-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='furniture_model',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='furniture_serial',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
