# Generated by Django 5.2 on 2025-04-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_alter_furniture_furniture_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='furniture_room',
            field=models.CharField(choices=[('2310', 'HR Director Room'), ('2311', 'HR TS Room'), ('2313', 'HR Staff Room'), ('231V', 'HR Visting Room'), ('2308', 'HR Conference Room'), ('231R', 'HR Rest Room')]),
        ),
    ]
