# Generated by Django 5.2 on 2025-05-09 16:37

import django_advance_thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_assetdesc_alter_furniture_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='thumbnail',
            field=django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
