# Generated by Django 5.2 on 2025-04-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_alter_furniture_furniture_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='furniture_qty',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
