# Generated by Django 5.2 on 2025-05-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_furniture_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='thumbnail_new',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='thumbnails'),
        ),
    ]
