# Generated by Django 5.2 on 2025-05-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_alter_furniture_furniture_qty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furniture',
            options={'ordering': ['-furniture_dt_receipt']},
        ),
    ]
