# Generated by Django 5.2 on 2025-05-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0005_alter_furniture_thumbnail_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='thumbnail',
        ),
    ]
