# Generated by Django 5.2 on 2025-05-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0005_alter_furniture_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='furniture_image',
            field=models.ImageField(blank=True, null=True, upload_to='assets'),
        ),
    ]
