# Generated by Django 5.2 on 2025-05-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0006_remove_furniture_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='furniture_image',
            field=models.ImageField(blank=True, default='D:\\vip_ref\\main_project\\imagesNo_Image/.jpg', null=True, upload_to='assets'),
        ),
    ]
