# Generated by Django 5.2 on 2025-05-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0007_alter_furniture_furniture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='furniture_image',
            field=models.ImageField(blank=True, default='D:\\vip_ref\\main_project\\images/No_Image.jpg', null=True, upload_to='assets'),
        ),
    ]
