# Generated by Django 5.2 on 2025-05-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0008_alter_furniture_furniture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='furniture_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture', to='furniture.assetdesc'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='thumbnail_new',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails_new'),
        ),
    ]
