# Generated by Django 5.2 on 2025-05-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0009_alter_furniture_furniture_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='thumbnail_new',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='thumbnails_new'),
        ),
    ]
