# Generated by Django 5.2 on 2025-05-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0010_alter_furniture_thumbnail_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furniture',
            options={'ordering': ['furniture_room', '-furniture_dt_receipt']},
        ),
    ]
