# Generated by Django 5.2 on 2025-04-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_dt', models.DateField()),
                ('reference_subject', models.CharField(max_length=200)),
                ('vip', models.CharField(max_length=60)),
                ('vip_sub', models.CharField(max_length=60)),
                ('reference_contents', models.TextField(blank=True, null=True)),
                ('inward_dt', models.DateField()),
                ('outward_ref', models.CharField(blank=True, max_length=60, null=True)),
                ('outward_dt', models.DateField()),
                ('subject_file', models.FileField(blank=True, null=True, upload_to='subject')),
                ('reply_file', models.FileField(blank=True, null=True, upload_to='reply')),
                ('pending', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Replied', 'Replied')], null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hod', models.ManyToManyField(blank=True, to='vip_ref.hod')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
