# Generated by Django 5.2 on 2025-04-23 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip_ref', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['-inward_dt']},
        ),
    ]
