# Generated by Django 5.2 on 2025-04-28 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_ref', '0002_alter_reference_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='hod_reply',
            field=models.ManyToManyField(blank=True, related_name='references_reply', to='vip_ref.hod'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='hod',
            field=models.ManyToManyField(blank=True, related_name='references', to='vip_ref.hod'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='vip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vip_ref.vip'),
        ),
    ]
