# Generated by Django 5.2 on 2025-04-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_ref', '0003_vip_reference_hod_reply_alter_reference_hod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='outward_dt',
            field=models.DateField(blank=True),
        ),
    ]
