# Generated by Django 5.2 on 2025-04-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_ref', '0004_alter_reference_outward_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reply_file',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/reply/blank.pdf', null=True, upload_to='reply'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='subject_file',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/subject/blank.pdf', null=True, upload_to='subject'),
        ),
    ]
