# Generated by Django 5.2 on 2025-04-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_ref', '0008_alter_reference_reply_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='outward_dt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
