# Generated by Django 5.2 on 2025-05-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_ref', '0009_alter_reference_outward_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='inward_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='inward_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='vip_sub',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
