# Generated by Django 5.2 on 2025-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_ref', '0010_reference_inward_ref_alter_reference_inward_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
