# Generated by Django 5.2 on 2025-06-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_ref', '0011_reference_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='vip_sub',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
