# Generated by Django 5.2 on 2025-06-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_ref', '0012_alter_reference_vip_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='hod',
            field=models.ManyToManyField(blank=True, related_name='references', to='vip_ref.hod', verbose_name='From HoD'),
        ),
    ]
