# Generated by Django 5.2 on 2025-06-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_ref', '0013_alter_reference_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='hod',
            field=models.ManyToManyField(blank=True, related_name='references', to='vip_ref.hod', verbose_name='Sent to HoD'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='hod_reply',
            field=models.ManyToManyField(blank=True, related_name='references_reply', to='vip_ref.hod', verbose_name='Received from HoD'),
        ),
    ]
