# Generated by Django 5.2 on 2025-06-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_ref', '0014_alter_reference_hod_alter_reference_hod_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='inward_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='inward_ref',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inward DP Reference No.'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='outward_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='outward_ref',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Outward Reference No.'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_dt',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference No. (VIP)'),
        ),
    ]
