# Generated by Django 5.2 on 2025-06-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_ref', '0015_alter_reference_inward_dt_alter_reference_inward_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='vip_sub',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of the Subordinate to VIP'),
        ),
    ]
